#!/bin/sh
# create the keepNote directory functions

hash_gen(){
  id=""
  for i in 8 4 4 4 12
   do
    hash=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $i | head -n 1)
    if [ $i -eq 12 ]
     then
       id=$id$hash
    else
       id="$id$hash-"
    fi
   done
 echo $id
}
# hashes used for templates
hash1=$(hash_gen)
hash2=$(hash_gen)
hash3=$(hash_gen)
hash4=$(hash_gen)
hash5=$(hash_gen)

create_keepNote(){
# create directory
dir=$1
mkdir $dir
#create node 
cat <<EOF > $dir/node.xml
<?xml version="1.0" encoding="UTF-8"?>
<node>
<version>6</version>
<dict>
  <key>attr_tables</key><array>
    <dict>
      <key>name</key><string>Default Table</string>
      <key>key</key><string>default</string>
      <key>attrs</key><array>
        <string>title</string>
        <string>created_time</string>
        <string>modified_time</string>
      </array>
    </dict>
  </array>
  <key>expanded</key><true/>
  <key>nodeid</key><string>$hash1</string>
  <key>modified_time</key><integer>$(date +%s)</integer>
  <key>content_type</key><string>application/x-notebook-dir</string>
  <key>created_time</key><integer>$(date +%s)</integer>
  <key>info_sort_dir</key><integer>1</integer>
  <key>title</key><string>$1</string>
  <key>column_widths</key><dict>
    <key>created_time</key><integer>150</integer>
    <key>modified_time</key><integer>1410</integer>
    <key>title</key><integer>150</integer>
  </dict>
  <key>attr_defs</key><array>
    <dict>
      <key>datatype</key><string>string</string>
      <key>default</key><string></string>
      <key>name</key><string>Duplicate of</string>
      <key>key</key><string>duplicate_of</string>
    </dict>
    <dict>
      <key>datatype</key><string>string</string>
      <key>default</key><string></string>
      <key>name</key><string>Title</string>
      <key>key</key><string>title</string>
    </dict>
    <dict>
      <key>datatype</key><string>string</string>
      <key>default</key><string></string>
      <key>name</key><string>Filename</string>
      <key>key</key><string>payload_filename</string>
    </dict>
    <dict>
      <key>datatype</key><string>bool</string>
      <key>default</key><true/>
      <key>name</key><string>Expaned</string>
      <key>key</key><string>expanded</string>
    </dict>
    <dict>
      <key>datatype</key><string>string</string>
      <key>default</key><string></string>
      <key>name</key><string>Node ID</string>
      <key>key</key><string>nodeid</string>
    </dict>
    <dict>
      <key>datatype</key><string>timestamp</string>
      <key>default</key><null/>
      <key>name</key><string>Modified time</string>
      <key>key</key><string>modified_time</string>
    </dict>
    <dict>
      <key>datatype</key><string>string</string>
      <key>default</key><string></string>
      <key>name</key><string>Icon open</string>
      <key>key</key><string>icon_open</string>
    </dict>
    <dict>
      <key>datatype</key><string>bool</string>
      <key>default</key><true/>
      <key>name</key><string>Expanded2</string>
      <key>key</key><string>expanded2</string>
    </dict>
    <dict>
      <key>datatype</key><string>string</string>
      <key>default</key><string></string>
      <key>name</key><string>Title Background Color</string>
      <key>key</key><string>title_bgcolor</string>
    </dict>
    <dict>
      <key>datatype</key><string>string</string>
      <key>default</key><string>application/x-notebook-dir</string>
      <key>name</key><string>Content type</string>
      <key>key</key><string>content_type</string>
    </dict>
    <dict>
      <key>datatype</key><string>timestamp</string>
      <key>default</key><null/>
      <key>name</key><string>Created time</string>
      <key>key</key><string>created_time</string>
    </dict>
    <dict>
      <key>datatype</key><string>integer</string>
      <key>default</key><integer>1</integer>
      <key>name</key><string>Folder sort direction</string>
      <key>key</key><string>info_sort_dir</string>
    </dict>
    <dict>
      <key>datatype</key><string>integer</string>
      <key>default</key><integer>9223372036854775807</integer>
      <key>name</key><string>Order</string>
      <key>key</key><string>order</string>
    </dict>
    <dict>
      <key>datatype</key><string>string</string>
      <key>default</key><string>order</string>
      <key>name</key><string>Folder sort</string>
      <key>key</key><string>info_sort</string>
    </dict>
    <dict>
      <key>datatype</key><string>string</string>
      <key>default</key><string></string>
      <key>name</key><string>Icon</string>
      <key>key</key><string>icon</string>
    </dict>
  </array>
  <key>version</key><integer>6</integer>
  <key>order</key><integer>0</integer>
  <key>info_sort</key><string>order</string>
</dict>
</node>
EOF

cat <<EOF > $dir/notebook.nbk
<?xml version="1.0" encoding="UTF-8"?>
<notebook>
<version>6</version>
<pref>
    <dict>
        <key>version</key><integer>6</integer>
        <key>quick_pick_icons</key><array>
            <string>folder.png</string>
            <string>folder-red.png</string>
            <string>folder-orange.png</string>
            <string>folder-yellow.png</string>
            <string>folder-green.png</string>
            <string>folder-blue.png</string>
            <string>folder-violet.png</string>
            <string>folder-grey.png</string>
            <string>note.png</string>
            <string>note-red.png</string>
            <string>note-orange.png</string>
            <string>note-yellow.png</string>
            <string>note-green.png</string>
            <string>note-blue.png</string>
            <string>note-violet.png</string>
            <string>note-grey.png</string>
            <string>star.png</string>
            <string>heart.png</string>
            <string>check.png</string>
            <string>x.png</string>
            <string>important.png</string>
            <string>question.png</string>
            <string>web.png</string>
            <string>note-unknown.png</string>
        </array>
        <key>index_dir</key><string></string>
        <key>colors</key><array>
            <string>#ff9999</string>
            <string>#ffcc99</string>
            <string>#ffff99</string>
            <string>#99ff99</string>
            <string>#99ffff</string>
            <string>#9999ff</string>
            <string>#ff99ff</string>
            <string>#ff0000</string>
            <string>#ffa300</string>
            <string>#ffff00</string>
            <string>#00ff00</string>
            <string>#00ffff</string>
            <string>#0000ff</string>
            <string>#ff00ff</string>
            <string>#7f0000</string>
            <string>#7f5100</string>
            <string>#7f7f00</string>
            <string>#007f00</string>
            <string>#007f7f</string>
            <string>#00007f</string>
            <string>#7f007f</string>
            <string>#ffffff</string>
            <string>#e5e5e5</string>
            <string>#bfbfbf</string>
            <string>#7f7f7f</string>
            <string>#3f3f3f</string>
            <string>#191919</string>
            <string>#000000</string>
        </array>
        <key>windows</key><dict>
            <key>ids</key><dict>
                <key>$hash2</key><dict>
                    <key>viewerid</key><string>$hash3</string>
                    <key>viewer_type</key><string>tabbed_viewer</string>
                </dict>
            </dict>
        </dict>
        <key>viewers</key><dict>
            <key>ids</key><dict>
                <key>$hash4</key><dict>
                    <key>selected_treeview_nodes</key><array>
                        <string>$hash5</string>
                    </array>
                    <key>selected_listview_nodes</key><array>
                        <string>$hash5</string>
                    </array>
                </dict>
                <key>$hash3</key><dict>
                    <key>tabs</key><array>
                        <dict>
                            <key>viewerid</key><string>$hash4</string>
                            <key>viewer_type</key><string>three_pane_viewer</string>
                            <key>name</key><string></string>
                        </dict>
                    </array>
                    <key>current_viewer</key><string>$hash4</string>
                </dict>
            </dict>
        </dict>
        <key>default_font</key><string>Sans 10</string>
    </dict>
</pref>
</notebook>
EOF
}

# create sub diretory for keepNote project
create_sub_kpn(){
# Random note hash
rhash=$(hash_gen)
# create directory
mydir=$2/$1
mkdir $mydir
#creade node 
cat <<EOF > $mydir/node.xml
<?xml version="1.0" encoding="UTF-8"?>
<node>
<version>6</version>
<dict>
  <key>expanded</key><false/>
  <key>title</key><string>$1</string>
  <key>nodeid</key><string>$rhash</string>
  <key>modified_time</key><integer>$(date +%s)</integer>
  <key>version</key><integer>6</integer>
  <key>content_type</key><string>text/xhtml+xml</string>
  <key>created_time</key><integer>$(date +%s)</integer>
  <key>info_sort_dir</key><integer>1</integer>
  <key>order</key><integer>2</integer>
  <key>info_sort</key><string>order</string>
  <key>icon</key><string>$(ls /usr/lib/python2.7/dist-packages/keepnote/images/node_icons/note-* | shuf  -n 1 | cut -d"/" -f 9)</string>
</dict>
</node>
EOF
# masscan 
udp=0
if [ "$4" = "on" ]; then
  if [ "$7" = "" ];then 
     masscan -p1-65535,U:1-65535 $1 --rate=$6 -e $5  > $mydir/masscan.txt
  else
     masscan -p1-65535,U:1-65535 $1 --rate=$6 -e $5 --router-ip $7 > $mydir/masscan.txt
  fi
  # Initializing variables
  ports_tcp=""
  ports_udp=""
  for port in $(cat $mydir/masscan.txt | grep -i open  | grep -i tcp |cut  -d " " -f 4 | cut -d "/" -f 1) ; do ports_tcp="$port,$ports_tcp"  ; done
  ports_tcp=$(echo $ports_tcp | sed 's/.$//'  )

  for port in $(cat $mydir/masscan.txt | grep -i open  | grep -i udp |cut  -d " " -f 4 | cut -d "/" -f 1) ; do ports_udp="$port,$ports_udp"  ; done
  ports_udp=$(echo $ports_udp | sed 's/.$//'  )
  #echo "ports scan : $ports_tcp"
  if [ $(echo $ports_tcp | wc -w)   -ne 0 ]; then
     nmap  -sV -sS -p $ports_tcp -T4 -sC  -oN $mydir/nmap.txt  $1
  fi
  if [ $(echo $ports_udp | wc -w)   -ne 0 ]; then
     nmap  -sV -sS -sU -p $ports_udp -T4 -sC  -oN $mydir/nmap2.txt  $1
     udp=1
  fi
else
  if [ "$3" = "l" ]; then
    nmap  -sV -sS  -T4 -oN $mydir/nmap.txt  $1
  else
    nmap  -sV -sS -p- -T4 -sC  -oN $mydir/nmap.txt  $1
  fi
fi
content=$(sed  's/.*/&<br>/'   $mydir/nmap.txt)
if [ "$udp" -ne 0 ]; then 
content="$content <br>Udp section : <br>  $(sed  's/.*/&<br>/'   $mydir/nmap2.txt) "
fi
cat <<EOF > $mydir/page.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><body>

$content

</body></html>
EOF
}

verify_cidr_param(){
if expr "$1" : '.*:.*' >/dev/null; then
   box="$(echo "$1" | cut -d: -f2)"
   if [ "$box" != "" ]; then
     verify_ip $(echo "$1" | cut -d: -f1)
     if [ $? -eq 0 ]; then
        echo "${RED}ERROR: parameter \"--cidr=$1\" is not correct. Ip part is wrong. \n${YELLOW}Right format: ip:MachineName${NC}\n"
        exit 2
     else
      box_name="$box"
      cidrip="$(echo "$1" | cut -d: -f1)"
      return 0
     fi
   else
     echo "${RED}ERROR: parameter \"--cidr=$1\" is not correct. You should define a machine name like: ip:MachineName${NC}\n"
     exit 2
   fi 
elif expr "$1" : '.*/.*' >/dev/null; then
   cidre=$(echo "$1" | cut -d"/" -f2)
   if [ "$cidre" != "" ] && [ $cidre -ge 1 -a $cidre -le 32 ]; then
     verify_ip  $(echo "$1" | cut -d"/" -f1)
     if [ $? -eq 0 ]; then
        echo "${RED}ERROR: parameter \"--cidr=$1\" is not correct. Ip part is wrong. \n${YELLOW}Right format: ip/cidr${NC}\n"
        exit 2     
     else
      return 0
     fi 
   else
       echo "${RED}ERROR: parameter \"--cidr=$1\" is not correct. '$cidre' should be an integer: 1<= cidr <=32 \n${YELLOW}Right format: ip/cidr${NC}\n" 
       exit 2
   fi   
fi
verify_ip  $1
if [ $? -eq 0 ]; then
   echo "${RED}ERROR: parameter \"--cidr=$1\" is not correct. Try a valid ip${NC}\n" 
   exit 2    
fi
}

verify_ip(){
if expr "$1" : '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' >/dev/null; then
  for i in 1 2 3 4; do
    if [ $(echo "$1" | cut -d. -f$i) -gt 255 ]; then
     return 0
    fi
  done
  return 1
else
    return 0
fi
}

verify_net_interface(){
if [ "$(ifconfig | grep $1 | cut -d: -f 1)" != "$1" ]; then
   echo "${RED}ERROR: parameter \"--interface=$1\" is not correct. Interface '$1' not found ${NC}\n" 
   exit 2
fi   
}

# color define
RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'

usage()
{
  if [ "$1" = "addto" ] ; then
     echo "Add a scan into a report already exists mode"
     echo "${GREEN}\nUsage:${NC}"
     echo "\t $0  addto [flags]"
     echo "\n${GREEN}Flags:${NC}"
     echo "\t -h, --help                   help for addto"
     echo "\t     --type=string            l|h  ['h' for huge scan(all ports) and 'l' for light scan(for commun ports)]           (light by default)"
     
     echo "\t     --masscan=string         on|no ['on' to enable masscan and 'no' to disable masscan]                             (enable by default)"
     echo "\t     --interface=string       The network interface to use with masscan, required if masscan is enabled"
     echo "\t     --rate=int               The speed of masscan, 150<value<1000                                                   (set to 150 by default)"
     echo "\t     --path=string            Path to a $0 report where the scan will be added                             <required>"
     echo "\t     --cidr=ip[:name]|cidr    ip or a cidr like 10.10.10.0/24, if name used it will be shown instead of the ip"
     echo "\t     --router-ip=ip           The gateway of the network interface if masscan can't found "
     echo "\t                                      it(failed to detect router for interface)"
     echo "\t     --ips-list=string        Path to a file which contains a list of ips to scan, you can define the name to show"
     echo "\t                                      in the report instead of the ip. Using space for the separation"
     echo "\n${GREEN}Examples :${NC}\n"
     echo "Default scan using Masscan with a rate of 500:  \n\t$0 addto --path=/path/to/exists/report/directory --rate=500 --interface=tun0  --cidr=10.10.10.0/16\n"
     echo "Default scan using Masscan with a rate of 500, scan one ip and define the name to show instead of ip:  \n\t$0 addto  --path=/path/to/exists/report/directory --rate=500 --interface=tun0  --cidr=10.10.10.12:Box12\n"
     echo "Default scan using Masscan and a list of ips, with the router ip gateway :  \n$0 addto  --path=/path/to/exists/report/directory --ips-list=file --interface=tun0  --router-ip=192.168.55.1 \n"
     echo "Create a report scan with a light scan without Masscan :\n$0 addto --masscan=no  --path=/path/to/exists/report/directory --cidr=10.10.10.14\n"
     echo "Create a report scan with a huge scan without Masscan :\n$0 addto --type=h  --masscan=no  --path=/path/to/exists/report/directory --cidr=10.10.10.0/24\n"
  elif [ "$1" = "new" ] ; then
     echo "Create a new report scan mode"
     echo "${GREEN}\nUsage:${NC}"
     echo "\t $0  new [flags]"
     echo "\n${GREEN}Flags:${NC}"
     echo "\t -h, --help                   help for new"
     echo "\t     --type=string            l|h  ['h' for huge scan(all ports) and 'l' for light scan(for commun ports)]           (light by default)"
     
     echo "\t     --masscan=string         on|no ['on' to enable masscan and 'no' to disable masscan]                             (enable by default)"
     echo "\t     --interface=string       The network interface to use with masscan, required if masscan is enabled"
     echo "\t     --rate=int               The speed of masscan, 150<value<1000                                                   (set to 150 by default)"
     echo "\t     --path=string            Path to a directory where the $0 will create the new report                  <required>"
     echo "\t     --name=string            The name of the report without space                                                   <Required>"
     echo "\t     --cidr=ip[:name]|cidr    ip or a cidr like 10.10.10.0/24, if name used it will be shown instead of the ip"
     echo "\t     --router-ip=ip           The gateway of the network interface if masscan can't found "
     echo "\t                                      it(failed to detect router for interface)"
     echo "\t     --ips-list=string        Path to a file which contains a list of ips to scan, you can define the name to show"
     echo "\t                                      in the report instead of the ip. Using space for the separation"
     echo  "\n${GREEN}Examples :${NC}\n"
     echo "Default scan using Masscan with a rate of 500:  \n\t$0 new --name=report-name --path=/path/to/report/destination_directory --rate=500 --interface=tun0  --cidr=10.10.10.0/16\n"
     echo "Default scan using Masscan with a rate of 500, scan one ip and define the name to show instead of ip:  \n\t$0 new --name=report-name --path=/path/to/report/destination_directory --rate=500 --interface=tun0  --cidr=10.10.10.12:Box12\n"
     echo "Default scan using Masscan and a list of ips, with the router ip gateway :  \n$0 new --name=report-name --path=/path/to/report/destination_directory --ips-list=file --interface=tun0  --router-ip=192.168.55.1 \n"
     echo "Create a report scan with a light scan without Masscan :\n$0 new --masscan=no --name=report-name --path=/path/to/report/destination_directory --cidr=10.10.10.14\n"
     echo "Create a report scan with a huge scan without Masscan :\n$0 new --type=h  --masscan=no --name=report-name --path=/path/to/report/destination_directory --cidr=10.10.10.0/24\n"
  else
     echo "${GREEN}\nUsage:${NC}"
     echo "\t $0  [command]"
     echo "${GREEN}Available Commands:${NC}"
     echo "\t ${YELLOW}new${NC}                     Create a new report scan"
     echo "\t ${YELLOW}addto${NC}                   Add a scan into a report already exists"
     echo "\t ${YELLOW}help${NC}                    Help about any command"
     echo "\n${GREEN}Flags:${NC}"
     echo "\t -h, --help                   help for $0"
     echo "\t     --type=string            l|h  ['h' for huge scan(all ports) and 'l' for light scan(for commun ports)]           (light by default)"
     echo "\t     --masscan=string         on|no ['on' to enable masscan and 'no' to disable masscan]                             (enable by default)"
     echo "\t     --interface=string       The network interface to use with masscan, required if masscan is enabled"
     echo "\t     --rate=int               The speed of masscan, 150<value<1000                                                   (set to 150 by default)"
     echo "\nUse '$0 [command] --help' for more information about a command."
  fi
}

# Main 
# verify the command 
if [ "$1" = "addto" ] || [ "$1" = "new" ] ; then
     cmd="$1"
else
     echo "${RED}ERROR: '$1'command does not exists${NC}"
     usage
     exit
fi 
shift

# Default values
scantype=l
masscan=on
interface=""
required=0
rate=150
file_ips=""
cidrip=""
router_ip=""
addto=""
newrep=""
gks=$(env | grep KEEPSCAN)
if [ "$gks" = "" ];then
  if [ -d  "/usr/share/KeepScan/template" ]; then
       KEEPSCAN="/usr/share/KeepScan"
  else
    if [ -d "./template" ]; then 
      KEEPSCAN="."
    else
      print "You should be in the KeepScan directory, or install it globally !!"
      exit 1 
    fi
  fi   
fi

while [ "$1" != "" ]; do    
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`
    case $PARAM in
        -h | --help | help)
            usage $cmd
            exit
            ;;
        --type)
             if [ "$VALUE" = "h" ] || [ "$VALUE" = "l" ] ; then
                scantype=$VALUE
             else 
                echo "${RED}ERROR: value \"$VALUE\" for parameter \"$PARAM\" is wrong${NC}\n"
                usage $cmd
                exit 1	
             fi
             ;;
        --name)
            name=$VALUE
            required=$((required+1))
            ;;
        --masscan)
             if [ "$VALUE" = "no" ] || [ "$VALUE" = "on" ]; then
                masscan=$VALUE
             else 
                echo "${RED}ERROR: value \"$VALUE\" for parameter \"$PARAM\" is wrong${NC}\n"
                usage $cmd
                exit 1
             fi
             ;;
        --interface)
            interface=$VALUE
            ;;
        --rate)
            re='^[0-9]+$'
            if [ "$VALUE" -gt 0 ] ; then
               rate=$VALUE
            else
               echo "${RED}ERROR: the value  \"$VALUE\" should be a positive integer only${NC}\n"
               usage $cmd
               exit 1
            fi
            ;;    
        --path)
            if [ -d "$VALUE" ]; then
              if expr "$VALUE" : '/.*/$' >/dev/null || [ ${#VALUE} = 1 ]; then
                 rootDir=$VALUE
              else
                 rootDir="$VALUE/"
              fi   
              required=$((required+1))
            else
              echo "${RED}ERROR: the path \"$VALUE\" is not a directory !!${NC}\n"
              usage $cmd
              exit 1
            fi
            ;;
        --ips-list)
            if [ -f "$VALUE" ]; then
              file_ips=$VALUE
              required=$((required+1))	
            else
              echo "${RED}ERROR: cannot access \"$VALUE\" no such file !!${NC}\n"
              usage $cmd
              exit 1
            fi
            ;;
        --cidr)
            cidrip=$VALUE
            required=$((required+1))
            ;;
        --router-ip)
            verify_ip $VALUE
            if [ $? -ne 0 ]; then
               router_ip="$VALUE"
            else
              echo "${RED}ERROR: the value  \"$VALUE\" is not a valid ip !!${NC}\n"
              usage $cmd
              exit 1
            fi
            ;;
        *)
            echo "${RED}ERROR: unknown parameter \"$PARAM\"${NC}\n"
            usage $cmd
            exit 1
            ;;
    esac
    shift
done

# Verify required params
if [ ! -z $cidrip ] && [ ! -z $file_ips ]; then
   echo "${RED}ERROR: Only use '--cidr' or '--ips-list'${NC}\n"
   usage $cmd
elif [ "$required" -ne 3 ] && [ "$cmd" = "new" ]; then
   echo "${RED}ERROR: parameters '--name' and '--path' and ('--cidr' or '--ips-list') are required${NC}\n"
   usage $cmd
   exit 1
elif [ "$required" -ne 2 ] && [ "$cmd" = "addto" ]; then
   echo "${RED}ERROR: parameters '--path' and ('--cidr' or '--ips-list') are required${NC}\n"
   usage $cmd
   exit 1
elif [ "$masscan" = "on" ] && [ "$interface" = "" ]; then
       echo "${RED}ERROR: the parameter '--interface' must be set when '--masscan' is enabled${NC}\n"
       usage $cmd
       exit 1
elif [ "$cmd" = "addto" ] && [ "$name" != "" ]; then
       echo "${RED}ERROR: do not use the  parameter '--name' with the 'addto' command${NC}\n"
       usage $cmd
       exit 1     
fi
# verify --cidr and --interface
box_name=""
if [ ! -z $cidrip ]; then 
  verify_cidr_param $cidrip
fi
if [ "$masscan" = "on" ]; then  
  verify_net_interface $interface
fi

#Verify if script run as root
if [ $(id -u)  -ne 0 ]; then 
        echo "${YELLOW}This script must be run as root, use sudo "$0" instead\n" 1>&2
        exit 1
fi

if [ "$cmd" = "new" ]; then
   dir="$rootDir$name"
   scanfile=$dir/scan.txt
   ipfile=$dir/boxes_ips.txt
elif [ -f "${rootDir}node.xml" ]; then  
    dir="$rootDir"
    scanfile="${dir}scan.txt"
    ipfile="${dir}boxes_ips.txt"
else
    echo "${RED}ERROR: parameter '--path', the directory '$rootDir' is not a valid keepnote report${NC}\n"
        exit 1
fi   
num_ips=0
echo $cidrip
echo $box_name
exit 1
if [ "$cmd" = "new" ]; then
   create_keepNote $dir && \
   cp -r $KEEPSCAN/template/__NOTEBOOK__ $dir/ 
fi
if [ "$file_ips" != "" ]; then
   cat $file_ips > $ipfile
fi
if [ "$box_name" != "" ]; then
   num_ips=$((num_ips+1))
   create_sub_kpn $cidrip $dir $scantype $masscan $interface $rate $router_ip
else
   nmap --top-ports 100 -oN $scanfile $cidrip 
   cat $scanfile |  grep -i "Nmap scan" | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])' > $ipfile 

   for ip in $(cat $ipfile );do
     verify_ip $ip
     if [ $? -ne 0 ]; then
        num_ips=$((num_ips+1))
        create_sub_kpn $ip $dir $scantype $masscan $interface $rate $router_ip
     else
       echo "${RED}\"$ip\" is not a valid ip${NC}"
     fi 
   done 
fi   
if [ $num_ips -gt 0 ]; then   
   echo "${GREEN} $0 successfully scaned $num_ips ip(s)"
   # If user want to let created report writable by a local user 
   echo "${YELLOW}If you want to let this report writable by the local user, tape :"
   echo "${GREEN}sudo chown -R \$(whoami):\$(whoami) $dir"
else
   echo "${RED} $0 does not find any valid ip to scan"
fi

